### ISSUE TITLE
Amendment to instructions on Rock, Paper, Scissors project

### ISSUE THREAD

**Issue by SarahSC** [CodeClub/python-curriculum#82]
![screen shot 2016-10-06 at 13 33 30](https://cloud.githubusercontent.com/assets/10815461/19152409/c0529b78-8bc9-11e6-9144-65840aab7b32.png)

The marked instructions are a repeat of instructions already given at the top of this screen shot.

@rik-cross

**Comment by martinpeck** [comment]
I see this is now closed, so feel free to ignore, but...

I agree that, as they were previously worded, there was duplication, but I wondered if it would be better to reword the two sets of text, rather than just remove one of them. The text that was removed...

> Putting a hash '#' at the beginning of a line tells Python not to run that line. 

... looked like it was trying to introduce the idea of commenting out code, and how adding and then removing print statements is a good way to debug code.

It felt like the first bit of text was giving the user instructions (to put a # infront of the print statement, or to remove it), while the second section of text was trying to explain *why* this works.

**Comment by tracygardner** [comment]
:-) I actually reworded it first and then decided to delete it. I've made a note that we might want to consider introducing commenting and its use in debugging more formally at some point. But I think there's enough to keep them busy in this project without focussing on that too much.
